export const FLAGS = {
  LOG_LEARNED_VOCAB: true,
  LOG_DISTRACTORS: false,
  LOG_WORDBANK: false,
  LOG_SEMANTIC_GROUPS: false,
  USE_NEW_DISTRACTOR_LOGIC: false,
  USE_NEW_WORDBANK_LOGIC: false,
  USE_NEW_GRAMMAR_OPTIONS: false,
};

