import { AudioMeaningStep } from "../../types";

/**
 * Internal helper function to generate audio-meaning steps
 * 
 * This is the implementation logic for audio-meaning step generation.
 * Exported for use by curriculum-helpers.ts wrapper.
 * 
 * Audio-meaning steps test vocabulary comprehension by playing audio
 * and asking the user to select the correct English meaning.
 * 
 * Distractors are auto-generated by WordBankService when
 * FLAGS.USE_LEARNED_VOCAB_IN_AUDIO_MEANING is enabled (current default).
 * 
 * @param vocabularyId - The target vocabulary item to test (e.g., "salam")
 * @param points - Points for the audio-meaning exercise (default: 2)
 * @param autoPlay - Whether to auto-play audio on load (default: undefined, component decides)
 * @returns AudioMeaningStep with vocabularyId and empty distractors array
 */
export function audioMeaningHelper(
  vocabularyId: string,
  points: number = 2,
  autoPlay?: boolean
): AudioMeaningStep {
  return {
    type: "audio-meaning",
    points,
    data: {
      vocabularyId,
      distractors: [], // Empty - WordBankService auto-generates when flag is ON
      autoPlay
    }
  };
}
