import { AudioSequenceStep } from "../../types";

/**
 * Internal helper function to generate audio-sequence steps
 * 
 * This is the implementation logic for audio-sequence step generation.
 * Exported for use by curriculum-helpers.ts wrapper.
 * 
 * Audio-sequence steps play a sequence of Persian words and ask the user
 * to select the English meanings in the correct order.
 * 
 * Word banks are auto-generated by WordBankService using semantic distractor strategy.
 * 
 * @param sequence - Array of vocabulary IDs in the order they should be played (e.g., ["salam", "chetori"])
 * @param expectedTranslation - English translation of the sequence (e.g., "Hello how are you")
 * @param points - Points for the audio-sequence exercise (default: 3)
 * @param autoPlay - Whether to auto-play audio sequence on load (default: undefined, component decides)
 * @param targetWordCount - Number of English words expected (overrides semantic unit calculation)
 * @param maxWordBankSize - Maximum number of options in word bank (default: 12)
 * @returns AudioSequenceStep with sequence and expectedTranslation
 */
export function audioSequenceHelper(
  sequence: string[],
  expectedTranslation: string,
  points: number = 3,
  autoPlay?: boolean,
  targetWordCount?: number,
  maxWordBankSize?: number
): AudioSequenceStep {
  return {
    type: "audio-sequence",
    points,
    data: {
      sequence,
      expectedTranslation,
      ...(autoPlay !== undefined && { autoPlay }),
      ...(targetWordCount !== undefined && { targetWordCount }),
      ...(maxWordBankSize !== undefined && { maxWordBankSize })
    }
  };
}

