import { TextSequenceStep } from "../../types";

/**
 * Internal helper function to generate text-sequence steps
 * 
 * This is the implementation logic for text-sequence step generation.
 * Exported for use by curriculum-helpers.ts wrapper.
 * 
 * Text-sequence steps display Finglish text and ask the user to select
 * English meanings in the correct order.
 * 
 * Word banks are auto-generated by WordBankService using semantic distractor strategy.
 * Points and maxWordBankSize have consistent defaults - always 3 points and 10 max size.
 * 
 * @param finglishText - Finglish phrase to display (e.g., "Salam chetori")
 * @param expectedTranslation - English translation to build (e.g., "Hello how are you")
 * @returns TextSequenceStep with finglishText and expectedTranslation
 */
export function textSequenceHelper(
  finglishText: string,
  expectedTranslation: string
): TextSequenceStep {
  return {
    type: "text-sequence",
    points: 3, // Consistent default
    data: {
      finglishText,
      expectedTranslation,
      maxWordBankSize: 10 // Consistent default
    }
  };
}

