import { TextSequenceStep } from "../../types";

/**
 * Internal helper function to generate text-sequence steps
 * 
 * This is the implementation logic for text-sequence step generation.
 * Exported for use by curriculum-helpers.ts wrapper.
 * 
 * Text-sequence steps display Finglish text and ask the user to select
 * English meanings in the correct order.
 * 
 * Word banks are auto-generated by WordBankService using semantic distractor strategy.
 * Points and maxWordBankSize have consistent defaults - always 3 points and 10 max size.
 * 
 * PHASE 8 FIX: Strips punctuation from expectedTranslation (commas, periods, etc.)
 * to ensure clean word matching without punctuation.
 * 
 * @param finglishText - Finglish phrase to display (e.g., "Salam chetori")
 * @param expectedTranslation - English translation to build (e.g., "Hello, how are you" → "Hello how are you")
 * @returns TextSequenceStep with finglishText and cleaned expectedTranslation
 */
export function textSequenceHelper(
  finglishText: string,
  expectedTranslation: string
): TextSequenceStep {
  // PHASE 8 FIX: Remove punctuation from expected translation
  // Removes commas, periods, question marks, exclamation marks, etc.
  const cleanedTranslation = expectedTranslation
    .replace(/[,\.!?;:]/g, '')  // Remove common punctuation
    .replace(/\s+/g, ' ')        // Normalize multiple spaces to single space
    .trim();                      // Remove leading/trailing spaces
  
  return {
    type: "text-sequence",
    points: 3, // Consistent default
    data: {
      finglishText,
      expectedTranslation: cleanedTranslation,
      maxWordBankSize: 10 // Consistent default
    }
  };
}

